### ISSUE TITLE
Move to MariaDB

### ISSUE THREAD

**Issue by sudheesh001** [gearsystems/publicportal#19]
Remove existing psql and move the code to run with mariaDB backend instead.

**Comment by kranthikiran01** [comment]
@sudheesh001 I moved to mariadb long back.....just install mariadb. No need to change any configs. Its that easy :heart:

**Comment by sudheesh001** [comment]
I know that, mariaDB driver should be the same to work with as mysql and starting mysql should essentially start mariaDB. Can you push those changes to the public portal so that it becomes easier, right now the DB_ENGINE is postgres

**Comment by kranthikiran01** [comment]
next push shall contain those changes :+1:  

Why are we using postgres :disappointed:

**Comment by sudheesh001** [comment]
Uses MySQL Driver ORM Driver itself. Safe to close.
