### ISSUE TITLE
PostgreSQL integration with PostGIS on the main test server

### ISSUE THREAD

**Issue by sudheesh001** [gearsystems/publicportal#4]

**Comment by sudheesh001** [comment]
As discussed @kranthikiran01 , Should we be going for `MariaDB` with `GIS` and the `DjangoGIS` integration ? Feel free to edit the Issue #4 heading for this purpose.

**Comment by kranthikiran01** [comment]
Lets postgres with postgis....we can port to maria later at any point of time

**Comment by kranthikiran01** [comment]
Stick to simple database and make the application stable. Later scale to postgresql once the application is shaped properly
